import type { AppRoute, User, Withdrawal } from '../type/AppType';

export const AppRoutes = {
  DASHBOARD: '/dashboard',
  WITHDRAWS: '/withdraws',
  GAZ: '/gaz',
  PROFILE: '/profile',
};

export const RouteList: AppRoute[] = [
  { path: AppRoutes.DASHBOARD, name: 'dashboard', displayName: 'Dashboard' },
  {
    path: AppRoutes.WITHDRAWS,
    name: 'withdraws',
    displayName: 'Withdraw history',
  },
  { path: AppRoutes.GAZ, name: 'gaz', displayName: 'Gaz' },
  { path: AppRoutes.PROFILE, name: 'profile', displayName: 'Profile' },
];

// -------------- Temporary Fake Data ----------------------
const users: User[] = [
  { id: 'u1', email: 'alice.johnson@example.com' },
  { id: 'u2', email: 'brian.smith@example.com' },
  { id: 'u3', email: 'carla.davis@example.com' },
];

export const rows: Withdrawal[] = [
  {
    id: '1',
    reason: 'ATM Withdrawal',
    date: new Date('2026-05-02'),
    location: 'New York',
    amount: 240.0,
    user: users[0],
  },
  {
    id: '2',
    reason: 'Groceries',
    date: new Date('2026-05-01'),
    location: 'Los Angeles',
    amount: 128.5,
    user: users[1],
  },
  {
    id: '3',
    reason: 'Gas',
    date: new Date('2026-04-30'),
    location: 'Chicago',
    amount: 42.3,
    user: users[2],
  },
  {
    id: '4',
    reason: 'Medical',
    date: new Date('2026-04-29'),
    location: 'Houston',
    amount: 315.2,
    user: users[0],
  },
  {
    id: '5',
    reason: 'Rent',
    date: new Date('2026-04-28'),
    location: 'San Francisco',
    amount: 1350.0,
    user: users[1],
  },
  {
    id: '6',
    reason: 'Utilities',
    date: new Date('2026-04-27'),
    location: 'Seattle',
    amount: 98.75,
    user: users[2],
  },
  {
    id: '7',
    reason: 'Subscription',
    date: new Date('2026-04-26'),
    location: 'Austin',
    amount: 22.99,
    user: users[0],
  },
  {
    id: '8',
    reason: 'Dining',
    date: new Date('2026-04-25'),
    location: 'Miami',
    amount: 76.4,
    user: users[1],
  },
  {
    id: '9',
    reason: 'Travel',
    date: new Date('2026-04-24'),
    location: 'Denver',
    amount: 519.0,
    user: users[2],
  },
  {
    id: '10',
    reason: 'Office Supplies',
    date: new Date('2026-04-23'),
    location: 'Boston',
    amount: 63.12,
    user: users[0],
  },
  {
    id: '11',
    reason: 'Shopping',
    date: new Date('2026-04-22'),
    location: 'Portland',
    amount: 184.7,
    user: users[1],
  },
  {
    id: '12',
    reason: 'Gym',
    date: new Date('2026-04-21'),
    location: 'San Diego',
    amount: 45.0,
    user: users[2],
  },
  {
    id: '13',
    reason: 'Insurance',
    date: new Date('2026-04-20'),
    location: 'Philadelphia',
    amount: 212.6,
    user: users[0],
  },
  {
    id: '14',
    reason: 'Education',
    date: new Date('2026-04-19'),
    location: 'Atlanta',
    amount: 540.0,
    user: users[1],
  },
  {
    id: '15',
    reason: 'Gift',
    date: new Date('2026-04-18'),
    location: 'Dallas',
    amount: 120.0,
    user: users[2],
  },
  {
    id: '16',
    reason: 'Home Repair',
    date: new Date('2026-04-17'),
    location: 'Phoenix',
    amount: 287.9,
    user: users[0],
  },
  {
    id: '17',
    reason: 'Entertainment',
    date: new Date('2026-04-16'),
    location: 'Las Vegas',
    amount: 89.1,
    user: users[1],
  },
  {
    id: '18',
    reason: 'Parking',
    date: new Date('2026-04-15'),
    location: 'San Jose',
    amount: 18.0,
    user: users[2],
  },
  {
    id: '19',
    reason: 'Pet Care',
    date: new Date('2026-04-14'),
    location: 'Orlando',
    amount: 65.55,
    user: users[0],
  },
  {
    id: '20',
    reason: 'Taxi',
    date: new Date('2026-04-13'),
    location: 'Nashville',
    amount: 31.25,
    user: users[1],
  },
];
