name: deploy-to-firebase-hosting
run-name: Build and deploy app to firebase hosting
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          npm install

      - name: Create .env file
        run: |
          echo "VITE_API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "VITE_AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}" >> .env
          echo "VITE_DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "VITE_PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env
          echo "VITE_STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}" >> .env
          echo "VITE_MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_APP_ID=${{ secrets.APP_ID }}" >> .env
          echo "VITE_MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }}" >> .env

      - name: Debug folder
        run: |
          ls

      - name: Build Vite App
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          channelId: live
