name: deploy-to-firebase-hosting

run-name: Build and deploy app to firebase hosting

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  check-dependencies-vulnerability:
    # Run when:
    # - manually triggered
    # - OR commit message ends with "cd:auto"
    if: >
      github.event_name == 'workflow_dispatch' ||
      endsWith(github.event.head_commit.message, 'cd:auto')
    uses: ./.github/workflows/vulnerabilities-checker.yml
    with:
      working-directory: '.'
      source: 'ci-cd'

  auto-update-dependencies-if-vulnerability-found:
    uses: ./.github/workflows/auto-deps-update.yml
    needs: check-dependencies-vulnerability
    if: needs.check-dependencies-vulnerability.outputs.has_vulnerability == 'true'
    secrets:
      PAT: ${{ secrets.PAT_SECRET }}
    with:
      working-dir: '.'
      should-run-unit-test: true

  unit-test:
    needs:
      [
        check-dependencies-vulnerability,
        auto-update-dependencies-if-vulnerability-found,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: install dep
        run: |
          npm install

      - name: run-test
        run: |
          npx vitest run --reporter=verbose

  deploy:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.API_KEY }}
          VITE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          VITE_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          VITE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.APP_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live
