name: deploy-to-firebase-hosting
run-name: Build and deploy app to firebase hosting
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Vite App
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.API_KEY }}
          VITE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          VITE_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          VITE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          VITE_MESSAGINE_SENDER_ID: ${{ secrets.MESSAGINE_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.APP_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          channelId: live
